import { GoogleGenAI, Modality, GenerateContentResponse } from "@google/genai";
import { MockupType } from '../types';

const IMAGE_MODEL_NAME = 'gemini-2.5-flash-image';


const getPromptForType = (mockupType: MockupType): string => {
  const printPrompt = `You are a photorealistic image modification expert.
INPUT: You will receive a single composite image showing a design placed on a product.
TASK: The design currently looks flat, like a sticker. Your job is to make the design look like a realistic, high-quality screen print on the product's material.
- Add realistic texture to the print that matches the underlying material (e.g., fabric weave).
- Apply lighting effects (shadows, highlights) so the print integrates seamlessly with the product.
- Make the print conform to the product's surface contours (curves, folds, seams).
CRITICAL RULE: You MUST NOT change the position, size, shape, rotation, or color of the design. Modify its texture and lighting ONLY. The final output must be the full image with the realistic print.`;

  const magentaMaskPrompt = `You are a high-precision photorealistic image processor.
INPUT: You will receive a single image of a product with a solid bright magenta (#FF00FF) shape overlaid on it.
TASK: Your only job is to replace the magenta area with a realistic [EFFECT] effect.
- The effect should look like it is carved into the product's material.
- The effect's color should be a natural, darkened shade of the product's material.
- It must have realistic depth, texture, and internal shadowing.
- It must conform to the surface contours and lighting of the product.
CRITICAL RULES:
- The boundaries of the magenta area are absolute. The effect MUST perfectly fill the magenta area with ZERO PIXEL DEVIATION.
- You MUST NOT change any part of the image outside the magenta area.
The final output must be the full image with the effect applied.`;

  switch (mockupType) {
    case MockupType.PRINT:
      return printPrompt;
    case MockupType.EMBOSS:
      return magentaMaskPrompt.replace('[EFFECT]', 'debossing (pressed into the material)') + `
ADDITIONAL DETAILS:
- The effect should look 'debossed' (pressed into) the material.
- It must have realistic depth and texture, with subtle internal shadowing.`;
    case MockupType.ENGRAVE:
    default:
      return magentaMaskPrompt.replace('[EFFECT]', 'laser engraving') + `
ADDITIONAL DETAILS:
- The effect should look like a laser engraving on the material.
- The engraved area should appear slightly darkened or burnt, typical of laser engraving.`;
  }
}

export const generateMockup = async (
    guideImage: string,
    mockupType: MockupType,
    apiKey: string,
  ): Promise<string> => {

  if (!apiKey) {
    throw new Error("API Key is missing.");
  }
  
  const ai = new GoogleGenAI({ apiKey });
  const prompt = getPromptForType(mockupType);
  
  // The image model expects the image data part to come BEFORE the text prompt part.
  const parts = [
    {
      inlineData: {
          data: guideImage.split(',')[1],
          mimeType: guideImage.startsWith('data:image/png') ? 'image/png' : 'image/jpeg',
      }
    },
    { text: prompt }
  ];


  try {
    const response: GenerateContentResponse = await ai.models.generateContent({
        model: IMAGE_MODEL_NAME,
        contents: {
          parts: parts,
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          const base64ImageBytes: string = part.inlineData.data;
          return `data:image/png;base64,${base64ImageBytes}`;
        }
    }
    
    throw new Error("No image was generated by the model.");

  } catch (error: any) {
    console.error("Error generating mockup with Gemini API:", error);
    if (error.message && (error.message.includes('API key not valid') || error.message.includes('API_KEY_INVALID'))) {
      throw new Error("API_KEY_INVALID");
    }
    throw new Error("Failed to communicate with the AI model.");
  }
};